services:
  - type: web
    name: diffusion-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python diffusion.py
    envVars:
      - key: GROQ_API_KEY
        sync: false